import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${playfair.className} min-h-full flex flex-col`}>
        <div className="absolute inset-0 opacity-10 pointer-events-none"
          style={{
            backgroundImage: "url('https://www.transparenttextures.com/patterns/asfalt-light.png')"
          }}
        ></div>
        <div className="absolute inset-0 backdrop-blur-[2px]"></div>
        {/* Gradient blur circles */}
        <div className="absolute -top-40 -left-40 w-80 h-80 bg-pink-300 opacity-30 blur-3xl rounded-full"></div>
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-red-200 opacity-30 blur-3xl rounded-full"></div>
        <div className="absolute top-1/3 -right-20 w-72 h-72 bg-pink-200 opacity-25 blur-3xl rounded-full"></div>
        
        {/* Decorative hearts for love */}
        <div className="absolute top-10 left-10 text-pink-300 opacity-30 text-4xl pointer-events-none">♥</div>
        <div className="absolute top-32 right-20 text-red-300 opacity-25 text-3xl pointer-events-none">♥</div>
        <div className="absolute bottom-20 left-1/4 text-pink-300 opacity-20 text-2xl pointer-events-none">♥</div>
        
        {/* Decorative academic/toga elements */}
        <div className="absolute top-1/4 right-10 text-purple-200 opacity-20 text-5xl pointer-events-none">✦</div>
        <div className="absolute bottom-1/3 right-1/3 text-purple-300 opacity-15 text-4xl pointer-events-none">✦</div>
        <div className="absolute bottom-10 right-10 text-purple-200 opacity-20 text-3xl pointer-events-none">⚜</div>
        
        {children}
      </body>
    </html>
  );
}
